site_name: 'Python FastAPI Application Documentation'
site_description: 'Main documentation for Python FastAPI features and framework APIs'
repo_url: https://github.com/okeyobia/python-fastapi-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting Started: 'docs/index.md'