replicaCount: 2

image:
  repository: okeyobia/python-fastapi-app
  tag: "e37e2823"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: fastapi.local

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
livenessProbe:
  httpGet:
    path: /health
    port: 80
readinessProbe:
  httpGet:
    path: /health
    port: 80